.cursor/rules/conventional-commits.mdc
.cursor/rules/docker-configuration.mdc
.cursor/rules/no-apologies-rule.mdc
.cursor/rules/no-summaries-rule.mdc
.cursor/rules/no-unnecessary-confirmations-rule.mdc
.cursor/rules/no-unnecessary-updates-rule.mdc
.cursor/rules/preserve-existing-code-rule.mdc
.cursor/rules/project-structure.mdc
.cursor/rules/service-configuration.mdc
.cursor/rules/single-chunk-edits-rule.mdc
.cursor/rules/verify-information-rule.mdc
.github/workflows/code-quality.yml
.gitignore

feat(rules): add code quality cursor rules
This PR adds a set of code quality cursor rules to improve AI interactions and maintain consistency across the project.
- Add no-apologies rule
- Add no-summaries rule
- Add no-unnecessary-confirmations rule
- Add no-unnecessary-updates rule
- Add preserve-existing-code rule
- Add single-chunk-edits rule
- Add verify-information rule
These rules will help:
- Maintain consistent and high-quality AI interactions
- Reduce unnecessary confirmations and updates
- Preserve existing code and functionality
- Ensure information is verified before presentation
- Streamline the editing process with single-chunk edits

feat(rules): add code quality cursor rules

---

.env.example
docker-compose.prod.yml
docker-compose.yml

- Added required environment variables for n8n, opensearch, postgresql, and temporal in docker-compose files
- Updated .env.example to remove unnecessary volume path configuration
- Ensured default values are set for environment variables to improve configuration flexibility

chore(docker,env): clean up env vars and defaults for n8n, opensearch, postgresql, temporal

---

docker-compose.prod.yml

- Removed PostgreSQL dependency for both n8n and Temporal services in `docker-compose.prod.yml`.
- Removed the OpenSearch service configuration to streamline the setup further.
These changes enhance the reliability of service dependencies in the production environment.

chore(docker): update n8n and Temporal service dependencies in production

---

docker-compose.yml

- Added a new environment variable for timezone (TZ) in the docker-compose.yml file to allow for timezone customization for the n8n service.
This change enhances the n8n service by enabling users to set their preferred timezone, improving scheduling and time-related functionalities.

feat(docker): add timezone configuration for n8n in Docker Compose

---

.github/CODEOWNERS

- Add CODEOWNERS file to automatically assign @killev as default reviewer
- Configure repository to follow GitHub's code ownership rules
This change helps streamline the review process by automatically requesting review from the designated code owner when PRs are opened.

chore: Add CODEOWNERS file with default owner

---

docker-compose.prod.yml

- Introduced a new environment variable `N8N_BLOCKED_NODES` in the `docker-compose.prod.yml` file to specify blocked nodes for the n8n service.
This change enhances the n8n service by allowing users to restrict certain nodes, improving security and control over workflows.

feat(docker): add blocked nodes configuration for n8n in production

---

.cursor/rules/temporal-project-structure.mdc

- Introduced a new markdown file defining the directory and documentation structure for Temporal-based workflows and workers.
- Outlined project structure, shared utilities, documentation requirements, best practices, and enforcement rules for creating new Temporal workers.
This addition enhances clarity and consistency in project organization for Temporal workflows.

feat: Add Temporal Project Structure Rule documentation

---

.github/workflows/code-quality.yml
Dockerfile.temporal
Dockerfile.temporal-worker-main
docker-compose.yml
workers/main/eslint.config.mjs
workers/main/package-lock.json
workers/main/package.json
workers/main/src/__tests__/index.test.ts
workers/main/src/index.ts
workers/main/tsconfig.json

- Updated the base image for the Temporal Dockerfile to version 1.27.2.
- Changed database configuration in `docker-compose.yml` to use `postgres12` and added a new environment variable for visibility database.
- Introduced a new Dockerfile for the Temporal worker, defining multi-stage builds for development and production environments.
- Enhanced healthcheck command in the Temporal Dockerfile for improved service monitoring.
- Added error handling in the main worker script to ensure unhandled errors are logged.
These changes improve the setup and configuration of the Temporal service and its workers, enhancing reliability and maintainability.

feat(docker): update Temporal setup and add worker configuration

---

workers/main/.env.test
workers/main/package-lock.json
workers/main/package.json
workers/main/src/__tests__/utils.test.ts
workers/main/src/common/utils.ts
workers/main/src/configs/index.ts
workers/main/src/configs/redmineDatabase.ts
workers/main/src/configs/worker.ts
workers/main/vitest.config.ts

- Added a new `.env.test` file for environment variable configuration.
- Implemented `validateEnv` function to ensure required environment variables are set, logging errors and exiting if validation fails.
- Created configuration schemas for Redmine database and Temporal settings using Zod for validation.
- Updated `package.json` and `package-lock.json` to include new dependencies for environment validation and database configuration.
- Added unit tests for the `validateEnv` function to ensure proper functionality.
These changes improve the robustness of the Temporal worker by enforcing environment variable validation and enhancing configuration management.

feat: Enhance environment validation and configuration for Temporal worker

---

workers/main/src/configs/index.ts
workers/main/src/configs/mongoDatabase.ts
workers/main/src/configs/slack.ts

- Introduced `mongoDatabase.ts` and `slack.ts` files containing configuration schemas for MongoDB and Slack integration.
- Updated `index.ts` to include the new schemas in the validation process.
These changes enhance the environment validation by incorporating MongoDB and Slack configurations, ensuring proper setup for integration.

feat: Add MongoDB and Slack configuration schemas for validation

---

workers/main/src/common/errors/FinAppRepositoryError.test.ts
workers/main/src/common/errors/FinAppRepositoryError.ts
workers/main/src/common/errors/index.ts

- Introduced `FinAppRepositoryError` class extending `AppError` to standardize error handling for financial application repository errors.
- Created `FinAppRepositoryError.test.ts` to validate the functionality of the new error class, ensuring proper message and name assignment.
- Updated the index file to export the new error class.
These additions enhance error management for the financial application and improve test coverage for error handling.

Add FinAppRepositoryError class with unit tests

---

workers/main/src/services/TargetUnit/queries.ts
workers/main/src/services/WeeklyFinancialReport/WeeklyFinancialReportRepository.ts

- Updated the date range logic in the TARGET_UNITS_QUERY to calculate the start date of the quarter dynamically, ensuring accurate reporting for target units.
- Adjusted the `composeWeeklyReportTitle` method to set the period start based on the current quarter, enhancing the clarity and accuracy of weekly financial reports.
These changes improve the accuracy of financial data retrieval and reporting in the application.

Refactor SQL query for improved date range logic

---

.gitignore

- Added entry to ignore the `data` directory within the `workers/main` path, which contains runtime and generated data. This change helps maintain a cleaner repository by preventing unnecessary files from being tracked.
These modifications enhance the project's file management and ensure that generated data does not clutter the version control system.

Update `.gitignore` to ignore data directory for main worker

---

workers/main/src/configs/weeklyFinancialReport.ts
workers/main/src/services/TargetUnit/queries.ts

- Add constants for Redmine custom field IDs to weeklyFinancialReport config
- Refactor TargetUnit query to support DepTech hours calculation
- Improve SQL structure for group and project time aggregation
These changes enhance the flexibility and accuracy of the weekly financial report generation process.

feat(TargetUnit): Add DepTech hours calculation and Redmine custom field IDs

---

.env.example
workers/main/.env.test
workers/main/src/configs/qbo.ts

Add QuickBooks Online OAuth2 configuration parameters to support the QBO integration for weekly financial reports.

Add OAuth2 parameters

---

.gitignore
CLAUDE.md
docs/user-guide/qbo_token_management.md

- Added entries to ignore the `.cursor/rules/isolation_rules/` directory and `memory-bank/`, ensuring that unnecessary files do not clutter the repository.
- This change enhances the project's file management by preventing the tracking of runtime and generated data.
These modifications contribute to a cleaner version control system.

Update .gitignore to include additional rules (#76)

---

workers/main/src/common/utils.test.ts
workers/main/src/common/utils.ts

- Introduced a new function `formatDateToISOString` in `utils.ts` to convert Date objects to ISO 8601 string format. This utility enhances date handling across the application, ensuring consistent date formatting.
These changes improve the utility functions available for date manipulation, facilitating better integration with APIs and data processing.

Add date formatting utility function (#76)

---

docker-compose.prod.yml

- Added `restart: unless-stopped` to the n8n service for improved reliability.
- Introduced environment variables `N8N_DEFAULT_BINARY_DATA_MODE` and `N8N_BINARY_DATA_STORAGE_PATH` to configure binary data handling.
- Cleaned up unnecessary whitespace in the configuration file for better readability.
Docs: https://docs.n8n.io/hosting/configuration/environment-variables/binary-data/
These changes enhance the stability and functionality of the n8n service in the production environment.

Update docker-compose.prod.yml to enhance n8n service configuration

---

workers/main/src/common/errors/OAuth2Error.test.ts
workers/main/src/common/errors/OAuth2Error.ts
workers/main/src/common/errors/index.ts

- Introduced a new error class `OAuth2Error` that extends `AppError`, providing a specific error handling mechanism for OAuth2-related issues.
- Added unit tests for `OAuth2Error` to verify the correct setting of message, name, and error code.
These changes enhance error management in the application by allowing for more granular handling of OAuth2 errors.

Add OAuth2Error class and corresponding tests

---

workers/main/src/configs/axios.test.ts
workers/main/src/configs/axios.ts
workers/main/src/configs/qbo.ts

- Introduced `axios.ts` to define the axios configuration with timeout, maxRetries, and headers.
- Added `axios.test.ts` to validate the properties and values of the axios configuration, ensuring it meets the expected structure and values.
These changes enhance the application's HTTP client configuration and ensure proper testing of the axios setup.

Add axios configuration and tests

---

workers/main/src/common/utils.test.ts
workers/main/src/common/utils.ts
workers/main/src/services/QBO/QBORepository.errorHandling.test.ts
workers/main/src/services/QBO/QBORepository.integration.test.ts
workers/main/src/services/QBO/QBORepository.test.ts
workers/main/src/services/QBO/QBORepository.ts
workers/main/src/services/QBO/index.test.ts
workers/main/src/services/QBO/index.ts
workers/main/src/services/QBO/types.test.ts
workers/main/src/services/QBO/types.ts

- Introduced `QBORepository` class to handle QuickBooks Online integration, including methods for fetching and aggregating customer revenue data from invoices.
- Added comprehensive unit tests for `QBORepository`, covering error handling, data aggregation, and retry logic for API calls.
- Created supporting types for `CustomerRevenueByRef` and `Invoice` to enhance type safety and clarity in the implementation.
These changes establish a robust foundation for the QBO integration, improving revenue reporting capabilities within the application.

Add QBORepository and related tests for effective revenue calculation
